### ISSUE TITLE
Should we publish this under the `@google` npm scope?

### ISSUE THREAD

**Issue by JustinBeckwith** [google/post-install-check#3]
I rather like the idea of keeping all of our npm modules under the `@google` scope.  Do folks have any opinions on moving us over there?

**Comment by ofrobots** [comment]
Mixed feelings about calling this `@google/something` on npm. That may make people think that this is specific to google projects, while it is a generally usable utility. This is the same rationale why `eventid` and `gts` are not in the Google npm scope.

I am in favor of some renames though. The term `post-install-check` doesn't seem descriptive to me. A better name would be something like `ts-install-check`.

**Comment by ofrobots** [comment]
This has been addressed.
